"""Add cancellation_reason to reservations.

Revision ID: 70412c1f9804
Revises: add_staff_devices
Create Date: 2025-11-20

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70412c1f9804'
down_revision = 'add_staff_devices'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reservations', sa.Column('cancellation_reason', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reservations', 'cancellation_reason')
    # ### end Alembic commands ###
