"""Add price_bs column to rooms table.

Revision ID: c7a8b9d0e1f2
Revises: 40cad4936546
Create Date: 2025-11-13 10:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7a8b9d0e1f2'
down_revision = '40cad4936546'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rooms', sa.Column('price_bs', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rooms', 'price_bs')
    # ### end Alembic commands ###
